;;; timu-spacegrey-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from timu-spacegrey-theme.el

(autoload 'timu-spacegrey-toggle-dark-light "timu-spacegrey-theme" "\
Toggle between \"dark\" and \"light\" `timu-spacegrey-flavour'." t)
(autoload 'timu-spacegrey-toggle-org-colors-intensity "timu-spacegrey-theme" "\
Toggle between intense and non intense colors for `org-mode'.
Customize `timu-spacegrey-org-intense-colors' the to achieve this. " t)
(autoload 'timu-spacegrey-toggle-mode-line-border "timu-spacegrey-theme" "\
Toggle between borders and no borders for the `mode-line'.
Customize `timu-spacegrey-mode-line-border' the to achieve this. " t)
(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "timu-spacegrey-theme" '("timu-spacegrey"))

;;; End of scraped data

(provide 'timu-spacegrey-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; timu-spacegrey-theme-autoloads.el ends here
